#!/bin/bash

# Lista los archivos y directorios (no ocultos) en el directorio actual, separados por comas
# y añade una barra ("/") al final de los directorios

ls -tm | awk -F', ' '
{
    for (i=1; i<=NF; i++) {
        gsub(/^[ \t]+|[ \t]+$/, "", $i); # Trim leading/trailing whitespace
        if (system("[ -d \"" $i "\" ]") == 0) {
            printf "%s/, ", $i
        } else {
            printf "%s, ", $i
        }
    }
}
END {print ""}
' | sed 's/, $//'

